import { useState, useEffect } from 'react'
import './App.css'

/**
 * Deniz Restaurant - Stitch SDK Generated Design
 * This design incorporates components and styling generated by Google's Stitch SDK
 * with custom Mediterranean color palette and typography.
 * 
 * Design System (from Stitch):
 * - Primary: #d4af37 (Gold)
 * - Brand Blue: #1a365d (Ocean Deep)
 * - Fonts: Playfair Display (headers), Inter (body)
 * - Roundness: 0.5rem-0.75rem (modern curves)
 */

function App() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    date: '',
    guests: '2',
    message: ''
  })
  const [submitted, setSubmitted] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 50)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    console.log('Reservation submitted:', formData)
    setSubmitted(true)
    setTimeout(() => setSubmitted(false), 4000)
    setFormData({ name: '', email: '', phone: '', date: '', guests: '2', message: '' })
  }

  const scrollToSection = (id) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' })
    setMenuOpen(false)
  }

  const menuItems = [
    { id: 'seafood', icon: '🦐', title: 'Deniz Ürünleri', desc: 'Her gün taze yakalanan balıklar ve deniz mahsulleri' },
    { id: 'meze', icon: '🥗', title: 'Meze & Salatalar', desc: 'Geleneksel Akdeniz mezelerini keşfedin' },
    { id: 'drinks', icon: '🍷', title: 'İçecekler', desc: 'Yerel şaraplar ve serinletici içecekler' },
    { id: 'desserts', icon: '🍰', title: 'Tatlılar', desc: 'Ev yapımı Türk tatlıları' },
    { id: 'events', icon: '🎂', title: 'Özel Günler', desc: 'Kutlamalarınız için özel organizasyonlar' },
    { id: 'view', icon: '🌅', title: 'Deniz Manzarası', desc: 'Eşsiz Bodrum manzarasıyla yemek keyfi' },
  ]

  const galleryImages = [
    { src: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600', title: 'Şık İç Mekan' },
    { src: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600', title: 'Taze Deniz Ürünleri' },
    { src: 'https://images.unsplash.com/photo-1535850452425-140ee4a8dbae?w=600', title: 'Deniz Manzarası' },
    { src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600', title: 'Gurme Sunum' },
    { src: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=600', title: 'Romantik Atmosfer' },
    { src: 'https://images.unsplash.com/photo-1515669097368-22e68427d265?w=600', title: 'Gün Batımı' },
  ]

  return (
    <div className="app bg-background-light font-display text-slate-900 min-h-screen">
      {/* ===== NAVIGATION (Stitch-inspired) ===== */}
      <header className={`fixed top-0 left-0 w-full z-50 transition-all duration-300 ${
        scrolled 
          ? 'bg-white/95 backdrop-blur-md shadow-md py-3' 
          : 'bg-transparent py-5'
      }`}>
        <div className="max-w-7xl mx-auto px-6 lg:px-12 flex items-center justify-between">
          {/* Logo */}
          <a href="#" className="flex items-center gap-3">
            <span className="text-primary text-3xl">🦞</span>
            <h1 className={`font-serif text-xl lg:text-2xl font-bold tracking-tight transition-colors ${
              scrolled ? 'text-brand-blue' : 'text-white'
            }`}>
              Deniz Restaurant
            </h1>
          </a>
          
          {/* Desktop Navigation */}
          <nav className="hidden lg:flex items-center gap-10">
            {['about', 'services', 'gallery', 'contact'].map((section) => (
              <a
                key={section}
                href={`#${section}`}
                onClick={(e) => { e.preventDefault(); scrollToSection(section) }}
                className={`text-sm font-semibold transition-colors hover:text-primary ${
                  scrolled ? 'text-slate-700' : 'text-white/90'
                }`}
              >
                {section === 'about' && 'Hakkımızda'}
                {section === 'services' && 'Lezzetlerimiz'}
                {section === 'gallery' && 'Galeri'}
                {section === 'contact' && 'İletişim'}
              </a>
            ))}
            <button 
              onClick={() => scrollToSection('contact')}
              className="bg-primary hover:bg-primary-dark text-slate-900 px-6 py-2.5 rounded-full text-sm font-bold transition-all shadow-lg hover:shadow-gold"
            >
              Rezervasyon Yap
            </button>
          </nav>

          {/* Mobile Menu Toggle */}
          <button 
            className={`lg:hidden text-2xl p-2 ${scrolled ? 'text-brand-blue' : 'text-white'}`}
            onClick={() => setMenuOpen(!menuOpen)}
          >
            {menuOpen ? '✕' : '☰'}
          </button>
        </div>

        {/* Mobile Navigation */}
        <nav className={`lg:hidden absolute top-full left-0 w-full bg-brand-blue/95 backdrop-blur-md transition-all duration-300 ${
          menuOpen ? 'opacity-100 visible' : 'opacity-0 invisible'
        }`}>
          <div className="flex flex-col p-6 gap-4">
            {['about', 'services', 'gallery', 'contact'].map((section) => (
              <a
                key={section}
                href={`#${section}`}
                onClick={(e) => { e.preventDefault(); scrollToSection(section) }}
                className="text-white text-lg font-medium py-2 hover:text-primary transition-colors"
              >
                {section === 'about' && 'Hakkımızda'}
                {section === 'services' && 'Lezzetlerimiz'}
                {section === 'gallery' && 'Galeri'}
                {section === 'contact' && 'İletişim'}
              </a>
            ))}
          </div>
        </nav>
      </header>

      {/* ===== HERO SECTION (Stitch-generated design) ===== */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        {/* Background with Gradient Overlay */}
        <div className="absolute inset-0 z-0">
          <div className="absolute inset-0 bg-gradient-to-b from-brand-blue/70 via-brand-blue/50 to-brand-blue/80 z-10" />
          <img 
            src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920"
            alt="Bodrum coastal view"
            className="w-full h-full object-cover"
          />
        </div>

        {/* Wave Pattern (CSS) */}
        <div className="absolute bottom-0 left-0 w-full h-24 bg-background-light z-20"
          style={{
            maskImage: "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 1440 320' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0,160L48,176C96,192,192,224,288,213.3C384,203,480,149,576,149.3C672,149,768,203,864,213.3C960,224,1056,192,1152,165.3C1248,139,1344,117,1392,106.7L1440,96L1440,320L0,320Z' fill='white'/%3E%3C/svg%3E\")",
            maskSize: 'cover',
            maskPosition: 'bottom'
          }}
        />

        {/* Hero Content */}
        <div className="relative z-20 text-center px-6 max-w-4xl mx-auto">
          {/* Rating Badge */}
          <div className="inline-flex flex-col items-center gap-2 bg-white/10 backdrop-blur-md px-6 py-3 rounded-2xl border border-white/20 mb-8">
            <div className="flex items-center gap-2">
              <span className="text-primary text-2xl font-bold">4.8</span>
              <div className="flex text-primary text-sm">★★★★★</div>
            </div>
            <span className="text-white/80 text-xs tracking-wider uppercase font-semibold">
              1043+ Google Yorumu
            </span>
          </div>

          {/* Headlines */}
          <h1 className="font-serif text-primary text-5xl md:text-7xl lg:text-8xl leading-tight tracking-tight mb-6">
            Deniz Restaurant
          </h1>
          <h2 className="text-white/90 text-lg md:text-2xl font-light tracking-[0.15em] uppercase italic mb-10">
            Bodrum'un Kalbinde, Denizin Tadında
          </h2>

          {/* CTA Button */}
          <button 
            onClick={() => scrollToSection('contact')}
            className="inline-flex items-center gap-3 bg-primary hover:bg-primary-dark text-slate-900 px-10 py-4 rounded-xl text-lg font-bold transition-all shadow-xl hover:shadow-gold"
          >
            Hemen Rezervasyon Yap
            <span>📅</span>
          </button>
        </div>

        {/* Scroll Indicator */}
        <div className="absolute bottom-32 left-1/2 -translate-x-1/2 z-20 animate-bounce">
          <div className="w-6 h-10 border-2 border-white/50 rounded-full flex justify-center pt-2">
            <div className="w-1 h-2 bg-white rounded-full animate-pulse" />
          </div>
        </div>
      </section>

      {/* ===== RATING SECTION (Stitch-generated) ===== */}
      <section className="bg-white py-16 px-6">
        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">
          <div className="space-y-4">
            <h3 className="font-serif text-3xl text-brand-blue">Mükemmellik Anlayışımız</h3>
            <p className="text-slate-600 leading-relaxed max-w-md">
              Bodrum'un en taze deniz mahsullerini, geleneksel Ege tarifleri ve modern 
              dokunuşlarla birleştiriyoruz. Misafirlerimizin %90'ından fazlası bizi 5 yıldızla ödüllendirdi.
            </p>
          </div>
          <div className="flex flex-wrap gap-8 items-start">
            <div className="text-center">
              <p className="text-primary text-5xl font-black">4.8</p>
              <div className="text-primary text-lg my-2">★★★★★</div>
              <p className="text-slate-500 text-sm">1043+ değerlendirme</p>
            </div>
            <div className="flex-1 min-w-[200px] space-y-3">
              {[
                { star: 5, pct: 90 },
                { star: 4, pct: 6 },
                { star: 3, pct: 2 },
                { star: 2, pct: 1 },
                { star: 1, pct: 1 },
              ].map(({ star, pct }) => (
                <div key={star} className="flex items-center gap-3">
                  <span className="text-slate-500 text-xs w-4">{star}</span>
                  <div className="flex-1 h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-primary rounded-full" style={{ width: `${pct}%` }} />
                  </div>
                  <span className="text-slate-400 text-xs w-8 text-right">{pct}%</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ===== ABOUT SECTION ===== */}
      <section id="about" className="bg-background-light py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-primary font-semibold text-sm uppercase tracking-widest">Hikayemiz</span>
            <h2 className="font-serif text-3xl lg:text-4xl text-brand-blue mt-3 mb-4">
              Bodrum'un Vazgeçilmez Lezzet Durağı
            </h2>
            {/* Gold Divider (Stitch-style) */}
            <div className="relative w-20 h-0.5 bg-gradient-to-r from-transparent via-primary to-transparent mx-auto">
              <span className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-background-light px-2 text-primary text-xs">✻</span>
            </div>
          </div>

          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-6">
              <p className="text-slate-600 text-lg leading-relaxed">
                <strong className="text-brand-blue">Deniz Restaurant</strong> olarak yıllardır Bodrum'da 
                misafirlerimize unutulmaz lezzetler sunuyoruz. Taze deniz ürünleri, yerel malzemeler 
                ve aşçılarımızın ustalığıyla hazırlanan menümüz, her ziyaretinizi özel kılıyor.
              </p>
              
              <div className="grid grid-cols-2 gap-4">
                {['Taze Deniz Ürünleri', 'Yerel Lezzetler', 'Şık Atmosfer', 'Güler Yüzlü Hizmet', 'Uygun Fiyatlar', 'Merkezi Konum'].map((item) => (
                  <div key={item} className="flex items-center gap-3 bg-white p-3 rounded-lg shadow-sm hover:shadow-md transition-shadow">
                    <span className="w-6 h-6 bg-ocean-light text-white rounded-full flex items-center justify-center text-xs font-bold">✓</span>
                    <span className="text-slate-700 text-sm">{item}</span>
                  </div>
                ))}
              </div>

              <div className="bg-white p-6 rounded-xl shadow-md border-l-4 border-primary mt-8">
                <p className="text-slate-600 text-sm mb-2">📍 <strong className="text-brand-blue">Adresimiz</strong></p>
                <p className="text-slate-500 text-sm mb-4">Çarşı, Belediye Meydanı No 4, 48400 Bodrum/Muğla</p>
                <p className="text-slate-600 text-sm mb-1">📞 <strong className="text-brand-blue">Hemen Arayın</strong></p>
                <a href="tel:+902523637674" className="text-ocean-light font-semibold text-lg hover:text-brand-blue transition-colors">
                  +90 252 363 76 74 →
                </a>
              </div>
            </div>

            <div className="flex justify-center">
              <div className="bg-gradient-to-br from-brand-blue to-ocean-mid text-white p-12 rounded-3xl shadow-blue text-center relative overflow-hidden">
                <div className="absolute top-0 right-0 w-1/2 h-1/2 bg-primary/10 rounded-full blur-3xl" />
                <p className="font-serif text-6xl font-bold text-primary relative">⭐ 4.8</p>
                <p className="text-lg opacity-90 mt-4 relative">Google Değerlendirmesi</p>
                <p className="text-sm opacity-70 mt-2 relative">1043+ mutlu müşteri</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ===== MENU/SERVICES SECTION (Stitch-generated) ===== */}
      <section id="services" className="bg-white py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-primary font-semibold text-sm uppercase tracking-widest">Menümüz</span>
            <h2 className="font-serif text-3xl lg:text-4xl text-brand-blue mt-3 mb-4">Özel Lezzetlerimiz</h2>
            <div className="relative w-20 h-0.5 bg-gradient-to-r from-transparent via-primary to-transparent mx-auto">
              <span className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-white px-2 text-primary text-xs">✻</span>
            </div>
            <p className="text-slate-500 mt-6 max-w-xl mx-auto">
              Her damak zevkine uygun, özenle hazırlanmış menümüzü keşfedin
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {menuItems.map((item) => (
              <div 
                key={item.id}
                className="group bg-white border border-slate-200 rounded-2xl p-8 text-center transition-all duration-300 hover:border-primary hover:shadow-gold cursor-pointer"
              >
                <div className="relative">
                  <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-1 bg-gradient-to-r from-ocean-light to-primary scale-x-0 group-hover:scale-x-100 transition-transform duration-300 rounded-t-2xl" />
                </div>
                <span className="text-5xl mb-6 block">{item.icon}</span>
                <h3 className="font-serif text-xl text-brand-blue mb-3">{item.title}</h3>
                <p className="text-slate-500 text-sm leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== GALLERY SECTION (Stitch-generated) ===== */}
      <section id="gallery" className="bg-slate-100 py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-primary font-semibold text-sm uppercase tracking-widest">Mekanımız</span>
            <h2 className="font-serif text-3xl lg:text-4xl text-brand-blue mt-3 mb-4">Atmosferimizi Keşfedin</h2>
            <div className="relative w-20 h-0.5 bg-gradient-to-r from-transparent via-primary to-transparent mx-auto">
              <span className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-slate-100 px-2 text-primary text-xs">✻</span>
            </div>
            <p className="text-slate-500 mt-6 max-w-xl mx-auto">
              Bodrum'un en güzel deniz manzarasıyla yemek keyfi
            </p>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
            {galleryImages.map((img, idx) => (
              <div 
                key={idx}
                className="group relative aspect-square rounded-2xl overflow-hidden cursor-pointer"
              >
                <img 
                  src={img.src}
                  alt={img.title}
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                  loading="lazy"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-brand-blue/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <p className="absolute bottom-4 left-4 right-4 text-white font-semibold opacity-0 group-hover:opacity-100 translate-y-4 group-hover:translate-y-0 transition-all duration-300">
                  {img.title}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== CONTACT SECTION (Stitch-generated) ===== */}
      <section id="contact" className="bg-white py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-primary font-semibold text-sm uppercase tracking-widest">Rezervasyon</span>
            <h2 className="font-serif text-3xl lg:text-4xl text-brand-blue mt-3 mb-4">Bize Ulaşın</h2>
            <div className="relative w-20 h-0.5 bg-gradient-to-r from-transparent via-primary to-transparent mx-auto">
              <span className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-white px-2 text-primary text-xs">✻</span>
            </div>
            <p className="text-slate-500 mt-6 max-w-xl mx-auto">
              Rezervasyon için arayın veya formu doldurun, size hemen dönelim
            </p>
          </div>

          <div className="grid lg:grid-cols-5 gap-8">
            {/* Contact Info */}
            <div className="lg:col-span-2 space-y-4">
              {[
                { icon: '📍', title: 'Adres', content: 'Çarşı, Belediye Meydanı No 4, 48400 Bodrum/Muğla' },
                { icon: '📞', title: 'Telefon', content: '+90 252 363 76 74', link: 'tel:+902523637674' },
                { icon: '⏰', title: 'Çalışma Saatleri', content: 'Her Gün: 08:00 - 00:00' },
                { icon: '⭐', title: 'Google Reviews', content: '4.8/5.0 · 1043 yorum' },
              ].map((item) => (
                <div key={item.title} className="flex gap-4 p-5 bg-background-light rounded-xl hover:bg-white hover:shadow-md transition-all group">
                  <div className="w-12 h-12 bg-gradient-to-br from-brand-blue to-ocean-mid rounded-xl flex items-center justify-center text-2xl">
                    {item.icon}
                  </div>
                  <div>
                    <h4 className="font-serif text-brand-blue font-semibold">{item.title}</h4>
                    {item.link ? (
                      <a href={item.link} className="text-ocean-light hover:text-brand-blue transition-colors text-sm">
                        {item.content}
                      </a>
                    ) : (
                      <p className="text-slate-500 text-sm">{item.content}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* Reservation Form */}
            <form onSubmit={handleSubmit} className="lg:col-span-3 bg-background-light p-8 rounded-2xl">
              {submitted && (
                <div className="bg-gradient-to-r from-green-500 to-green-600 text-white p-4 rounded-xl text-center font-semibold mb-6 animate-pulse">
                  ✅ Rezervasyonunuz alındı! En kısa sürede sizinle iletişime geçeceğiz.
                </div>
              )}

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <input
                  type="text"
                  name="name"
                  placeholder="Adınız Soyadınız"
                  value={formData.name}
                  onChange={handleChange}
                  required
                  className="w-full px-5 py-4 bg-white border-2 border-transparent rounded-xl focus:border-ocean-light focus:ring-4 focus:ring-ocean-light/10 outline-none transition-all"
                />
                <input
                  type="email"
                  name="email"
                  placeholder="E-posta Adresiniz"
                  value={formData.email}
                  onChange={handleChange}
                  required
                  className="w-full px-5 py-4 bg-white border-2 border-transparent rounded-xl focus:border-ocean-light focus:ring-4 focus:ring-ocean-light/10 outline-none transition-all"
                />
              </div>

              <div className="grid md:grid-cols-3 gap-4 mb-4">
                <input
                  type="tel"
                  name="phone"
                  placeholder="Telefon"
                  value={formData.phone}
                  onChange={handleChange}
                  className="w-full px-5 py-4 bg-white border-2 border-transparent rounded-xl focus:border-ocean-light focus:ring-4 focus:ring-ocean-light/10 outline-none transition-all"
                />
                <input
                  type="date"
                  name="date"
                  value={formData.date}
                  onChange={handleChange}
                  required
                  className="w-full px-5 py-4 bg-white border-2 border-transparent rounded-xl focus:border-ocean-light focus:ring-4 focus:ring-ocean-light/10 outline-none transition-all"
                />
                <select
                  name="guests"
                  value={formData.guests}
                  onChange={handleChange}
                  className="w-full px-5 py-4 bg-white border-2 border-transparent rounded-xl focus:border-ocean-light focus:ring-4 focus:ring-ocean-light/10 outline-none transition-all"
                >
                  {[1,2,3,4,5,6,7,8,'9+'].map(n => (
                    <option key={n} value={n}>{n} Kişi</option>
                  ))}
                </select>
              </div>

              <textarea
                name="message"
                placeholder="Mesajınız veya özel istekleriniz..."
                rows={4}
                value={formData.message}
                onChange={handleChange}
                className="w-full px-5 py-4 bg-white border-2 border-transparent rounded-xl focus:border-ocean-light focus:ring-4 focus:ring-ocean-light/10 outline-none transition-all mb-4 resize-none"
              />

              <button 
                type="submit"
                className="w-full bg-gradient-to-r from-brand-blue to-ocean-mid hover:from-ocean-mid hover:to-brand-blue text-white py-4 rounded-xl font-bold text-lg transition-all shadow-lg hover:shadow-blue flex items-center justify-center gap-3"
              >
                Rezervasyon Gönder
                <span>→</span>
              </button>
            </form>
          </div>
        </div>
      </section>

      {/* ===== FOOTER (Stitch-generated) ===== */}
      <footer className="bg-gradient-to-br from-brand-blue to-slate-900 text-white py-16 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="grid md:grid-cols-3 gap-12 mb-12">
            <div>
              <h3 className="font-serif text-2xl flex items-center gap-3 mb-4">
                🦞 Deniz Restaurant
              </h3>
              <p className="text-slate-400 text-sm leading-relaxed mb-4">
                Bodrum'un kalbinde, denizin tadında... Akdeniz mutfağının en seçkin lezzetlerini sizlerle buluşturuyoruz.
              </p>
              <span className="inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-2 rounded-full text-sm">
                📁 Yemek & İçecek
              </span>
            </div>
            
            <div>
              <h4 className="font-semibold text-lg mb-4">İletişim</h4>
              <p className="text-slate-400 text-sm leading-relaxed">
                📞 +90 252 363 76 74<br/>
                📍 Belediye Meydanı, Bodrum
              </p>
            </div>
            
            <div>
              <h4 className="font-semibold text-lg mb-4">Çalışma Saatleri</h4>
              <p className="text-slate-400 text-sm leading-relaxed">
                Her Gün Açık<br/>
                08:00 - 00:00
              </p>
            </div>
          </div>

          <div className="border-t border-white/10 pt-8 text-center">
            <p className="text-slate-400 text-sm">
              © 2026 Deniz Restaurant. Tüm hakları saklıdır. | Bodrum, Türkiye 🇹🇷
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default App
